/* RODO Store V4 — curated catalog + ownership experience. */
(() => {
    'use strict';

    const STORE_FEATURES = [
        { id: 'feature_journal_folders', title: 'تنظيم اليوميات', kicker: 'اليوميات', desc: 'نظّم يومياتك ونوتاتك داخل فولدرات من غير ما تغيّر طريقة الكتابة نفسها.', cost: 1200, icon: 'folder-kanban', kind: 'feature', target: 'يومياتي' },
        { id: 'feature_advanced_stats', title: 'إحصاءات متقدمة', kicker: 'الإحصاءات', desc: 'طبقة أعمق من الإحصاءات الموجودة: اتجاهات ومقارنات وقراءة أوضح لتقدمك مع الوقت.', cost: 1800, icon: 'chart-no-axes-combined', kind: 'feature', target: 'الإحصاءات' },
        { id: 'feature_focus_presets', title: 'إعدادات التركيز', kicker: 'التركيز', desc: 'احفظ طرق التركيز التي تناسبك، وابدأ جلسة بإعداداتها بدل إعادة ضبطها كل مرة.', cost: 1400, icon: 'timer-reset', kind: 'feature', target: 'التركيز' },
        { id: 'feature_goal_milestones', title: 'مراحل الأهداف', kicker: 'الأهداف', desc: 'حوّل الهدف الكبير إلى مراحل واضحة تقدر تتابعها واحدة واحدة.', cost: 1600, icon: 'milestone', kind: 'feature', target: 'الأهداف' }
    ];
    const PRODUCT_IDS = ['theme_graphite','theme_paper','theme_midnight','avatar_v4_01','avatar_v4_02','avatar_v4_03','avatar_v4_04','avatar_v4_05','avatar_v4_06','title_bashmohandes','title_doctor','title_businessman'];
    let activeSection='home';
    let detailOpen=false;
    const feature = id => STORE_FEATURES.find(p=>p.id===id)||null;
    const coreItem = id => typeof STORE_CATALOG!=='undefined' ? STORE_CATALOG.find(p=>p.id===id)||null : null;
    const esc=v=>typeof escapeHTML==='function'?escapeHTML(v):String(v??'');
    const money=v=>Number(v).toLocaleString('en-US');
    function ensure(){
        if(!state.store||typeof state.store!=='object') state.store={};
        const store=state.store;
        if(!store.v4Features||typeof store.v4Features!=='object'||Array.isArray(store.v4Features)) store.v4Features={};
        const f=store.v4Features;
        if(!Array.isArray(f.owned)) f.owned=[];
        if(!Array.isArray(f.active)) f.active=[];
        if(!f.data||typeof f.data!=='object'||Array.isArray(f.data)) f.data={};
        f.owned=[...new Set(f.owned.map(String).filter(id=>feature(id)))];
        f.active=[...new Set(f.active.map(String).filter(id=>f.owned.includes(id)))];
        return f;
    }
    function toast(m,t='info'){ if(typeof showToast==='function') showToast(m,t); }
    function appearance(){return PRODUCT_IDS.map(coreItem).filter(Boolean).filter(p=>p.storeV4===true);}
    function owned(id){return state.store.ownedItems.includes(id)}
    function activeAppearance(id){const p=coreItem(id);return p&&typeof isStoreItemActive==='function'&&isStoreItemActive(p)}
    function activeFeature(id){return ensure().active.includes(id)}
    function route(id,label){return `<button type="button" class="${activeSection===id?'is-active':''}" data-sv4-section="${id}" aria-selected="${activeSection===id}">${esc(label)}</button>`}
    function subnav(){const total=ensure().owned.length+appearance().filter(p=>owned(p.id)).length;return `<nav class="sv4-nav" role="tablist" aria-label="المتجر">${route('home','الرئيسية')}${route('features','الميزات')}${route('appearance','المظهر')}${route('collection',total?`مقتنياتي · ${total}`:'مقتنياتي')}</nav>`}
    function art(p){
        if(p.kind==='feature') return `<div class="sv4-art feature-art"><i data-lucide="${esc(p.icon)}"></i><span></span></div>`;
        if(p.type==='theme') return `<div class="sv4-art theme-art ${esc(p.themeCode)}"><div></div><div></div><div></div><strong>${esc(p.title)}</strong></div>`;
        if(p.type==='avatar') {const av=AVATARS_DATA.find(a=>a.id===p.avatarId);return `<div class="sv4-art avatar-art">${av?av.svg:''}</div>`}
        return `<div class="sv4-art title-art"><span>${esc(p.label||p.title)}</span></div>`;
    }
    function stateOf(p){if(p.kind==='feature')return{owned:ensure().owned.includes(p.id),active:activeFeature(p.id)};return{owned:owned(p.id),active:activeAppearance(p.id)};}
    function card(p){const s=stateOf(p);const buyable=Number(state.coins)>=Number(p.cost);const action=s.owned?(p.kind==='feature'?`<button type="button" data-sv4-toggle-feature="${esc(p.id)}" class="sv4-action ${s.active?'muted':'primary'}">${s.active?'مفعّلة':'تفعيل'}</button>`:`<button type="button" data-sv4-toggle-appearance="${esc(p.id)}" class="sv4-action ${s.active?'muted':'primary'}">${s.active?'مستخدمة':'تجهيز'}</button>`):`<button type="button" data-sv4-product="${esc(p.id)}" class="sv4-action ${buyable?'primary':'muted'}">${buyable?'عرض المنتج':'عرض المنتج'}</button>`;return `<article class="sv4-card ${s.active?'active':''}" data-sv4-product="${esc(p.id)}">${art(p)}<div class="sv4-card-body"><span>${esc(p.kind==='feature'?p.kicker:(p.type==='theme'?'ثيم':p.type==='avatar'?'أفاتار':'لقب'))}</span><h3>${esc(p.title)}</h3><p>${esc(p.desc)}</p><div class="sv4-card-foot"><strong>${s.owned?'مملوك':`${money(p.cost)} <small>عملة</small>`}</strong>${action}</div></div></article>`}
    function mount(){const host=document.getElementById('view-store');if(!host)return null;let root=host.querySelector('.rodo-store-v4');if(!root){root=document.createElement('div');root.className='rodo-store-v4';host.prepend(root)}host.querySelectorAll(':scope > *:not(.rodo-store-v4)').forEach(el=>el.classList.add('rodo-store-v4-legacy-hidden'));return root}
    function bindIcons(root){if(window.lucide?.createIcons) lucide.createIcons({root})}
    function home(root){const f=STORE_FEATURES.slice(0,2);const themes=appearance().filter(p=>p.type==='theme');const total=ensure().owned.length+appearance().filter(p=>owned(p.id)).length;root.innerHTML=`<section class="sv4-hero"><div><span class="sv4-eyebrow">RODO STORE</span><h1>خلي RODO على مزاجك.</h1><p>ميزات تضيف قيمة حقيقية، ومظهر تختاره أنت. المتجر صغير عن قصد — وكل حاجة فيه لها سبب.</p><div class="sv4-balance"><span>رصيدك</span><strong>${money(state.coins)}</strong><small>عملة</small></div></div><div class="sv4-hero-visual" aria-hidden="true"><span></span><span></span><b>R</b></div></section><nav class="sv4-nav" role="tablist" aria-label="المتجر">${route('home','الرئيسية')}${route('features','الميزات')}${route('appearance','المظهر')}${route('collection',`مقتنياتي${total?` · ${total}`:''}`)}</nav><section class="sv4-routes"><button data-sv4-section="features"><i data-lucide="sparkles"></i><div><span>FEATURES</span><strong>وسّع الأقسام التي تستخدمها</strong><p>ميزات تشتريها مرة واحدة، وتظهر داخل القسم الذي تنتمي إليه.</p></div><i data-lucide="arrow-left"></i></button><button data-sv4-section="appearance"><i data-lucide="palette"></i><div><span>APPEARANCE</span><strong>غيّر شكل تجربتك</strong><p>ثيمات، أفاتارات، وألقاب قليلة — وكل واحدة لها شخصية.</p></div><i data-lucide="arrow-left"></i></button></section><section class="sv4-section"><header><div><span>مختارات</span><h2>حاجات تستاهل تشوفها.</h2></div><button data-sv4-section="features">كل الميزات</button></header><div class="sv4-grid two">${f.map(card).join('')}</div></section><section class="sv4-section"><header><div><span>THEMES</span><h2>3 عوالم، 3 مزاجات.</h2></div><button data-sv4-section="appearance">استكشف المظهر</button></header><div class="sv4-grid three">${themes.map(card).join('')}</div></section>`;bindIcons(root)}
    function features(root){root.innerHTML=`${subnav()}<header class="sv4-page-head"><div><span>FEATURES</span><h1>وسّع RODO.</h1><p>ميزات تضيف شيئًا لقسم موجود أصلًا. لا نبيع أقسامًا منفصلة ولا أدوات منفصلة.</p></div><div class="sv4-balance compact"><span>رصيدك</span><strong>${money(state.coins)}</strong><small>عملة</small></div></header><div class="sv4-grid two">${STORE_FEATURES.map(card).join('')}</div><div class="sv4-note"><i data-lucide="info"></i><span>الملكية منفصلة عن التفعيل. إيقاف الميزة لا يحذف بياناتها.</span></div>`;bindIcons(root)}
    function appearancePage(root){const themes=appearance().filter(p=>p.type==='theme'),avs=appearance().filter(p=>p.type==='avatar'),titles=appearance().filter(p=>p.type==='title');root.innerHTML=`${subnav()}<header class="sv4-page-head"><div><span>APPEARANCE</span><h1>شكل RODO… على طريقتك.</h1><p>3 ثيمات، 6 أفاتارات، و3 ألقاب فقط في البداية. قليل، لكن متصمم بعناية.</p></div><div class="sv4-balance compact"><span>رصيدك</span><strong>${money(state.coins)}</strong><small>عملة</small></div></header><section class="sv4-section"><header><div><span>THEMES</span><h2>كل ثيم له شخصيته.</h2></div></header><div class="sv4-grid three">${themes.map(card).join('')}</div></section><section class="sv4-section"><header><div><span>AVATARS</span><h2>6 شخصيات بأسلوب واحد.</h2></div></header><div class="sv4-grid six">${avs.map(card).join('')}</div></section><section class="sv4-section"><header><div><span>TITLES</span><h2>ألقاب بسيطة لها وزن.</h2></div></header><div class="sv4-grid three">${titles.map(card).join('')}</div></section>`;bindIcons(root)}
    function collection(root){const f=ensure();const fo=STORE_FEATURES.filter(p=>f.owned.includes(p.id));const ao=appearance().filter(p=>owned(p.id));root.innerHTML=`${subnav()}<header class="sv4-page-head"><div><span>MY COLLECTION</span><h1>مقتنياتك.</h1><p>كل ما اشتريته موجود هنا. التفعيل منفصل عن الملكية، والعناصر القديمة لا نحذفها.</p></div><div class="sv4-balance compact"><span>رصيدك</span><strong>${money(state.coins)}</strong><small>عملة</small></div></header><section class="sv4-collection"><header><span>FEATURES</span><b>${fo.length}</b></header>${fo.length?fo.map(p=>`<div class="sv4-owned-row"><div class="owned-icon"><i data-lucide="${esc(p.icon)}"></i></div><div><span>${esc(p.kicker)}</span><strong>${esc(p.title)}</strong><small>${activeFeature(p.id)?'مفعّلة':'مملوكة'}</small></div><button data-sv4-toggle-feature="${esc(p.id)}">${activeFeature(p.id)?'إلغاء التفعيل':'تفعيل'}</button></div>`).join(''):`<div class="sv4-empty">لسه مفيش ميزات مملوكة.</div>`}</section><section class="sv4-collection"><header><span>APPEARANCE</span><b>${ao.length}</b></header><div class="sv4-owned-grid">${ao.length?ao.map(p=>`<article class="sv4-owned-card"><div>${art(p)}</div><strong>${esc(p.title)}</strong><small>${activeAppearance(p.id)?'مستخدمة الآن':'مملوكة'}</small><button data-sv4-toggle-appearance="${esc(p.id)}">${activeAppearance(p.id)?'إلغاء':'تجهيز'}</button></article>`).join(''):`<div class="sv4-empty">لسه مفيش تخصيصات مملوكة.</div>`}</div></section><div class="sv4-legacy"><i data-lucide="archive"></i><div><strong>مقتنيات سابقة محفوظة</strong><span>العناصر القديمة التي اشتريتها لم نحذفها. فقط مش ظاهرة في الـcatalog الجديد.</span></div></div>`;bindIcons(root)}
    function render(){ensure();const root=mount();if(!root)return;if(activeSection==='home')home(root);else if(activeSection==='features')features(root);else if(activeSection==='appearance')appearancePage(root);else collection(root)}
    function openDetail(id){const p=feature(id)||coreItem(id);if(!p)return;const existing=document.getElementById('sv4-detail');if(existing)existing.remove();const isFeat=Boolean(feature(id));const s=stateOf({...p,kind:isFeat?'feature':'appearance'});const buyable=!s.owned&&Number(state.coins)>=Number(p.cost);const el=document.createElement('div');el.id='sv4-detail';el.className='sv4-backdrop';el.innerHTML=`<section class="sv4-detail" role="dialog" aria-modal="true"><button data-sv4-close class="sv4-close" aria-label="إغلاق"><i data-lucide="x"></i></button><div class="sv4-detail-art">${art({...p,kind:isFeat?'feature':'appearance'})}</div><div class="sv4-detail-copy"><span>${esc(isFeat?p.kicker:(p.type==='theme'?'ثيم':p.type==='avatar'?'أفاتار':'لقب'))}</span><h2>${esc(p.title)}</h2><p>${esc(p.desc)}</p>${p.type==='theme'&&p.trait?`<div class="sv4-theme-trait"><span>لمسة ${esc(p.title)}</span><strong>${esc(p.trait)}</strong></div>`:''}<div class="sv4-detail-price"><span>${s.owned?'مملوك':'السعر'}</span><strong>${s.owned?'—':money(p.cost)} ${s.owned?'':'<small>عملة</small>'}</strong></div><div class="sv4-detail-actions">${s.owned?(isFeat?`<button data-sv4-detail-toggle-feature="${esc(id)}" class="primary">${s.active?'إلغاء التفعيل':'تفعيل'}</button>`:`<button data-sv4-detail-toggle-appearance="${esc(id)}" class="primary">${s.active?'إلغاء التجهيز':'تجهيز'}</button>`):`<button data-sv4-detail-buy="${esc(id)}" class="primary" ${buyable?'':'disabled'}>${buyable?'اقتناء':'رصيدك لا يكفي'}</button>`}<button data-sv4-close class="secondary">إلغاء</button></div></div></section>`;document.body.appendChild(el);detailOpen=true;bindIcons(el)}
    function closeDetail(){document.getElementById('sv4-detail')?.remove();detailOpen=false}
    function buyFeature(id){const p=feature(id);if(!p||isFeatureOwned(id))return false;if(state.coins<p.cost){toast(`ينقصك ${money(p.cost-state.coins)} عملة لاقتناء «${p.title}».`,'info');return false}const ok=typeof executeStoreTransaction==='function'&&executeStoreTransaction(()=>{const f=ensure();if(f.owned.includes(id)||state.coins<p.cost)return false;state.coins-=p.cost;f.owned.push(id);return true});if(ok){toast(`تم اقتناء «${p.title}».`,'success');render()}return ok}
    function isFeatureOwned(id){return ensure().owned.includes(id)}
    function onFeatureToggle(id){const f=ensure();if(!f.owned.includes(id))return;const enabled=!f.active.includes(id);f.active=enabled?[...f.active,id]:f.active.filter(x=>x!==id);saveState();render();window.dispatchEvent(new CustomEvent('rodo:premium-feature-change',{detail:{id:String(id),enabled}}));}
    function handle(event){const t=event.target instanceof Element?event.target.closest('[data-sv4-section],[data-sv4-product],[data-sv4-buy],[data-sv4-toggle-feature],[data-sv4-toggle-appearance],[data-sv4-detail-buy],[data-sv4-detail-toggle-feature],[data-sv4-detail-toggle-appearance],[data-sv4-close]'):null;if(!t)return;if(t.dataset.sv4Close!==undefined){closeDetail();return}if(t.dataset.sv4Section){activeSection=t.dataset.sv4Section;render();return}if(t.dataset.sv4Product){openDetail(t.dataset.sv4Product);return}if(t.dataset.sv4Buy){const id=t.dataset.sv4Buy;feature(id)?buyFeature(id):buyAppearance(id);return}if(t.dataset.sv4ToggleFeature){onFeatureToggle(t.dataset.sv4ToggleFeature);return}if(t.dataset.sv4ToggleAppearance){const id=t.dataset.sv4ToggleAppearance;activeAppearance(id)?deactivateAppearance(id):activateAppearance(id);return}if(t.dataset.sv4DetailBuy){const id=t.dataset.sv4DetailBuy;const ok=feature(id)?buyFeature(id):buyAppearance(id);if(ok)closeDetail();return}if(t.dataset.sv4DetailToggleFeature){onFeatureToggle(t.dataset.sv4DetailToggleFeature);closeDetail();return}if(t.dataset.sv4DetailToggleAppearance){const id=t.dataset.sv4DetailToggleAppearance;activeAppearance(id)?deactivateAppearance(id):activateAppearance(id);closeDetail();return}}
    function buyAppearance(id){if(typeof buyStoreItem!=='function')return false;const before=owned(id);if(before)return false;buyStoreItem(id);render();return owned(id)}
    function activateAppearance(id){if(typeof activateStoreItem!=='function')return false;activateStoreItem(id);render();return true}
    function deactivateAppearance(id){if(typeof deactivateStoreItem!=='function')return false;deactivateStoreItem(id);render();return true}
    function init(){ensure();const host=document.getElementById('view-store');if(!host)return;host.addEventListener('click',handle);if(document.documentElement.dataset.rodoStoreV4DetailBound!=='true'){document.documentElement.dataset.rodoStoreV4DetailBound='true';document.addEventListener('click',e=>{const target=e.target instanceof Element?e.target.closest('[data-sv4-detail-buy],[data-sv4-detail-toggle-feature],[data-sv4-detail-toggle-appearance],[data-sv4-close]'):null;if(target){handle(e);return}if(e.target?.id==='sv4-detail')closeDetail()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&detailOpen)closeDetail()})}render();window.RODO_STORE_V4={render,openDetail,features:STORE_FEATURES,isFeatureOwned:isFeatureOwned,isFeatureActive:activeFeature,getFeature:feature}}
    if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
